import { writeFileSync, mkdirSync, readdirSync } from 'fs'
import { join, basename } from 'path'

export function writeImportScript(outputDir: string): string {
  mkdirSync(outputDir, { recursive: true })

  const files = readdirSync(outputDir)
  const nodeFiles = files.filter((f) => f.startsWith('nodes_') && f.endsWith('.csv'))
  const relFiles = files.filter((f) => f.startsWith('rels_') && f.endsWith('.csv'))

  const nodeArgs = nodeFiles.map((f) => `  --nodes="${f}" \\`).join('\n')
  const relArgs = relFiles.map((f) => `  --relationships="${f}" \\`).join('\n')

  const script = `#!/bin/bash
# source2graph — Neo4j bulk import script
# Generated by s2g analyze
#
# Usage:
#   1. Stop Neo4j: neo4j stop
#   2. Run this script from the output directory: cd "${outputDir}" && bash neo4j-import.sh
#   3. Start Neo4j: neo4j start
#
# Or use neo4j-admin with a custom database name:
#   neo4j-admin database import full <db-name> [options below]

neo4j-admin database import full neo4j \\
${nodeArgs}
${relArgs}
  --overwrite-destination=true

echo "Import complete. Start Neo4j and run: MATCH (n) RETURN labels(n), count(*)"
`

  const scriptPath = join(outputDir, 'neo4j-import.sh')
  writeFileSync(scriptPath, script, { encoding: 'utf-8', mode: 0o755 })
  return scriptPath
}
